### ISSUE TITLE
feature request - use the selection

### ISSUE THREAD

**Issue by illbebach** [johnnytemp/vscode-ts-whitespace-converter#1]
I suggest use a selection area, if one exists.  Your whitespace converter works great.  But I would like it to not apply to the entire file.  I see two options:
1. make a new command that only applies to the selection
2. change the behavior of the existing command to apply only to the selection, if one exists.  Of course document this new behavior. 

The difficulty with 2 above is if there are multiple selection areas active.  Thanks again.

**Comment by johnnytemp** [comment]
Thanks. I will give a try.

**Comment by illbebach** [comment]
don't worry about it.  Was easy enough to do by pasting the text I wanted into another buffer.  Thanks

**Comment by johnnytemp** [comment]
Released version 1.2.1 for this feature.
